### ISSUE TITLE
How to use this with capacitor 6?

### ISSUE THREAD

**Issue by alexconstantin** [ionic-team/capacitor-google-maps#5]
Is there a way to make this work with the latest version of capacitor?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: afon@0.0.1
npm ERR! Found: @capacitor/core@6.0.0
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^5.0.0" from @capacitor/google-maps@5.4.1
npm ERR! node_modules/@capacitor/google-maps
npm ERR!   @capacitor/google-maps@"^5.4.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by eric-horodyski** [comment]
Hey @alexconstantin, our team's waiting on some updates from dependencies of this plugin before we can push out a v6. Apologies for the inconvenience.

**Comment by jcesarmobile** [comment]
We are waiting for a release of some google maps native dependencies to add Swift Package Manager support and ship with everything up to date.

For the moment you can install the RC version with `npm install @capacitor/google-maps@next`, but have in mind that the final version will require iOS 14 (while Capacitor itself still allows iOS 13) because of the google maps dependencies requiring iOS 14 or newer.

**Comment by jlgc77** [comment]
Perfect, I generate my app for version 14 onwards.
So it's not a problem for me.
Thank you very much for answering.
